apiVersion: apps/v1
kind: Deployment
metadata:
  name: bebop
  namespace: bebop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bebop
  template:
    metadata:
      labels:
        app: bebop
    spec:
      containers:
        - name: bebop
          image: public.ecr.aws/e3r0w7j9/bebop:latest
          args:
            - serve
          ports:
            - containerPort: 8080
              name: bebop
      nodeSelector:
        kubernetes.io/arch: amd64
