name: Build Bebop

on: [push, pull_request]

jobs:
  lint:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: vet
        run: go vet ./...
      - name: fmt
        run: test -z $(gofmt -l .)

  test:
    strategy:
      matrix:
        go-version: ["1.18.x", "1.19.x"]
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: build
        run: go build ./...
      - name: unit tests
        run: go test ./... -v
